=== nftstorage/metaplex-auth/src/metadata/metadata-schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "symbol": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "seller_fee_basis_points": {
        "type": "number"
      },
      "image": {
        "type": "string"
      },
      "animation_url": {
        "type": "string"
      },
      "external_url": {
        "type": "string"
      },
      "attributes": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "trait_type": {
              "type": "string"
            },
            "value": {
              "anyOf": [
                { "type": "string" },
                { "type": "number" }
              ]
            },
            "display_type": {
              "type": "string"
            },
            "max_value": {
              "type": "number"
            },
            "trait_count": {
              "type": "number"
            }
          }
        }
      },
      "properties": {
        "type": "object",
        "properties": {
          "files": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
              	"uri": {
                  "type": "string"
                },
                "type": {
                  "type": "string"
                },
                "cdn": {
                  "type": "boolean"
                }
              }
            }
          },
          "category": {
            "type": "string"
           },
           "creators": {
             "type": "array",
             "items": {
               "type": "object",
               "properties": {
                 "address": {
                   "type": "string"
                  },
                  "share": {
                    "type": "number"
                  }
               }
             }
           }
         }
      },
      "collection": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "family": {
            "type": "string"
          }
        }
      }
    },
      "required": ["name", "symbol"]
}

=== nftstorage/metaplex-auth/test/fixtures/nfts/03-load-directory-nested/0/0.json
{
  "name": "Test NFT.Storage Metaplex NFT #0",
  "symbol": "PLTEST",
  "description": "Just a test, nothing to see here",
  "seller_fee_basis_points": 0,
  "image": "0.png",
  "properties": {
    "files": [
      {
        "uri": "0.png",
        "type": "image/png"
      }
    ],
    "category": "image",
    "creators": [
      {
        "address": "3eoKfwCQ4jMBD5CEpLM8aCTZVN7wGQ9KTUBHhksmaZNh",
        "share": 100
      }
    ]
  }
}

=== nftstorage/metaplex-auth/test/fixtures/nfts/01-simple-example/token.json
{
  "name": "Test NFT.Storage Metaplex NFT",
  "symbol": "PLTEST",
  "description": "Just a test, nothing to see here",
  "seller_fee_basis_points": 0,
  "image": "",
  "properties": {
    "files": [
      {
        "uri": "token.png",
        "type": "image/png"
      }
    ],
    "category": "image",
    "creators": [
      {
        "address": "3eoKfwCQ4jMBD5CEpLM8aCTZVN7wGQ9KTUBHhksmaZNh",
        "share": 100
      }
    ]
  }
}
